name: linting, testing, building
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project in production mode
        run: npm run build:prod
      - name: tinting TypeStript
        run: npm run lint:ts
      - name: tinting SCSS
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      
